events {
    worker_connections 1024;
}

http {
    upstream api_gateway {
        # Docker's internal DNS will resolve this to the IP addresses 
        # of all replicas of the 'api-gateway' service.
        server api-gateway:3000;
    }

    server {
        listen 3000;

        location / {
            proxy_pass http://api_gateway;
            proxy_set_header Host $host;
            proxy_set_header Light-Step-Id $http_light_step_id;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Increase timeouts for load testing
            proxy_connect_timeout 10s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }

        # Health check for Nginx itself
        location /nginx-health {
            return 200 'Nginx is healthy';
        }
    }
}
